### ISSUE TITLE
What does createdatabase.py do?

### ISSUE THREAD

**Issue by twhyntie** [ameirshaa/sortcluster#2]
Hi @ameirshaa,

Apologies, I'm struggling to see what `createdatabase.py` is doing. Please could you update the `README.md` file or add detailed comments to `createdatabase.py` to explain to the uninitiated user (e.g. me :smile:) exactly what's going on and what `cluster.txt` represents?

It might also be nice to have some `print` statements so the user can follow what's going on at each stage of the code.

Thanks, @twhyntie

**Comment by ameirshaa** [comment]
Hi @twhyntie,

Sure thing! Can I edit createdatabase.py in github,com itself or do I have to edit somewhere else and then reupload? 

Many thanks,

@ameirshaa

**Comment by twhyntie** [comment]
@ameirshaa I would edit the code in a fresh clone of the repository, creating a new branch as described in the guide [here](https://gist.github.com/blackfalcon/8428401). Then you can run your code as you go to make sure it is doing what you think it is doing :smile:

(Note that the _branch_ feature does what you were essentially doing with the `timepixcode_eval` folder - you are not making changes to the `master` version of the code, but working on a test version. If all is good with the branch, it is then merged into the `master` branch.)

Great work, thanks!

**Comment by ameirshaa** [comment]
Hi @twhyntie,
I have created a new branch and added more explanation to the code and some print statements as well. Hope this helps! If not, just let me know!

**Comment by ameirshaa** [comment]
@twhyntie Done! And I have deleted the redundant if statements and merged the two branches!
